
DELETE FROM GIAO_DICH;
DELETE FROM HOA_DON;
DELETE FROM DAT_COC;


DELETE FROM DAT_PHONG;


DBCC CHECKIDENT ('GIAO_DICH', RESEED, 0);
DBCC CHECKIDENT ('HOA_DON', RESEED, 0);
DBCC CHECKIDENT ('DAT_COC', RESEED, 0);
DBCC CHECKIDENT ('DAT_PHONG', RESEED, 0);


UPDATE PHONG 
SET trangThai = N'Trống';